---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-volumesecret
spec:
  containers:
  - name: volumesecret
    image: redis
    volumeMounts:
    - name: volumesecret
      mountPath: "/etc/volumesecret"
      readOnly: true
  volumes:
  - name: volumesecret
    secret:
      secretName: mysecret
...
